// Styles hoisted from XpsProWorkbench.tsx (Phase 1 refactor). Legacy
// `Grade: / SNR` line style dropped — `ProQualityCard` owns the readout.

import type { CSSProperties } from 'react'
import { TYPO } from '../../../lib/typography-inline'

export const S = {
  errBox: { padding: 20, color: 'var(--color-red)' } as CSSProperties,
  left: {
    flex: 1,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
  } as CSSProperties,
  energyStrip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 14px',
    background: 'var(--color-bg-sidebar)',
    borderBottom: '1px solid var(--color-border)',
    fontSize: TYPO.xs,
  } as CSSProperties,
  energyLabel: {
    color: 'var(--color-text-secondary)',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    fontSize: TYPO.xxs,
  } as CSSProperties,
  energySep: { color: 'var(--color-text-muted)' } as CSSProperties,
  energyUnit: {
    color: 'var(--color-text-muted)',
    fontSize: TYPO.xxs,
  } as CSSProperties,
  chartWrap: {
    flex: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    position: 'relative',
  } as CSSProperties,
  emptyChart: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    color: 'var(--color-text-muted)',
  } as CSSProperties,
  shiftLine: {
    fontSize: TYPO.xxs,
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-mono)',
    padding: '2px 0',
  } as CSSProperties,
  xpsPeakTable: {
    marginTop: 8,
    maxHeight: 200,
    overflowY: 'auto',
    border: '1px solid var(--color-border)',
    borderRadius: 3,
    background: 'var(--color-bg-panel)',
  } as CSSProperties,
  xpsPeakHead: {
    display: 'grid',
    gridTemplateColumns: '30px 1fr 1fr 1fr',
    padding: '4px 8px',
    fontSize: TYPO.xxs,
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    borderBottom: '1px solid var(--color-border)',
  } as CSSProperties,
  xpsPeakRow: {
    display: 'grid',
    gridTemplateColumns: '30px 1fr 1fr 1fr',
    padding: '3px 8px',
    fontSize: TYPO.xs,
    fontFamily: 'var(--font-mono)',
    color: 'var(--color-text-primary)',
  } as CSSProperties,
  peakDefCard: {
    padding: 6,
    background: 'var(--color-bg-panel)',
    border: '1px solid var(--color-border)',
    borderRadius: 3,
    marginBottom: 4,
  } as CSSProperties,
  peakDefLabel: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    color: 'var(--color-text-primary)',
    fontSize: TYPO.xs,
    fontWeight: 600,
  } as CSSProperties,
  peakDefType: {
    fontSize: TYPO['2xs'],
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  } as CSSProperties,
  peakDefDelBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--color-red)',
    cursor: 'pointer',
    padding: 2,
  } as CSSProperties,
  peakDefGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: 4,
    marginTop: 4,
  } as CSSProperties,
  quantTable: {
    marginTop: 8,
    border: '1px solid var(--color-border)',
    borderRadius: 3,
    background: 'var(--color-bg-panel)',
  } as CSSProperties,
  quantHead: {
    display: 'grid',
    gridTemplateColumns: '1fr 60px',
    padding: '4px 8px',
    fontSize: TYPO.xxs,
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    borderBottom: '1px solid var(--color-border)',
  } as CSSProperties,
  quantRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 60px',
    padding: '4px 8px',
    fontSize: TYPO.xs,
    fontFamily: 'var(--font-mono)',
  } as CSSProperties,
  lookupList: {
    marginTop: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } as CSSProperties,
  lookupRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr auto',
    gap: 6,
    padding: '3px 6px',
    fontSize: TYPO.xxs,
  } as CSSProperties,
  tabPlaceholder: {
    padding: '16px 14px',
    fontSize: TYPO.xs,
    color: 'var(--color-text-muted)',
    lineHeight: 1.5,
  } as CSSProperties,
}
