// Structure → native engine cell templates.
//
// Whereas `compute-simulate-templates.ts` wraps every simulation in a
// pymatgen / ASE Python cell (good for "one click → runnable, via a
// uniform surface"), these templates produce cells whose bodies are
// the native engine input — `cp2k` for CP2K, `structure-code` Python
// that materialises a LAMMPS `.data` + `.in` script via ASE for
// LAMMPS. The goal is "grab something a collaborator on the command
// line could paste into cp2k.psmp / lmp directly".
//
// LAMMPS-as-native-cell isn't a clean fit in one notebook cell (LAMMPS
// has no way to read its data file from stdin; you need two files on
// disk and a run command to glue them). So we cheat: a small Python
// cell writes both files to /tmp and subprocess-execs `lmp`. The user
// sees a single-cell run path and can edit pair_style / pair_coeff
// before clicking Run again.

import type {
  ComputeCellKind,
  ComputeCellProvenance,
} from '../types/artifact'
import type { ParsedCif } from './cif'

// ── Public shape (mirrors compute-simulate-templates.ts) ───────────

export type ExportKind = 'lammps' | 'cp2k'

export interface ExportTargetInput {
  /** ACTIVE_CIFS slug — must match `slugForCifKey(artifact.title || formula || id)`. */
  slug: string
  /** Display label for titling / commentary (e.g. "BaTiO3"). */
  formula: string
  /** Parsed CIF — required for the CP2K path (coords are inlined into
   *  the .inp) and for the LAMMPS path's species-mass map. Callers
   *  that only have the CIF text should pass `parseCif(text)`. */
  parsedCif: ParsedCif
  /** Source structure artifact id for provenance back-links. Optional
   *  because this flow is also reachable from a cell's own build
   *  output (not-yet-saved-as-artifact). */
  parentStructureId?: string
}

export interface ExportTemplate {
  cellKind: ComputeCellKind
  title: string
  code: string
  provenance: ComputeCellProvenance
}

export function buildExportTemplate(
  kind: ExportKind,
  input: ExportTargetInput,
): ExportTemplate {
  switch (kind) {
    case 'lammps':
      return buildLammpsExportCell(input)
    case 'cp2k':
      return buildCp2kExportCell(input)
  }
}

// ── LAMMPS (Python-bridged) ─────────────────────────────────────────

/**
 * Spawn a `structure-code` Python cell that uses ASE to materialise a
 * LAMMPS data file (`/tmp/data.<slug>`) and a template input script
 * (`/tmp/in.<slug>`), then runs `lmp -in …`. The pair_style and
 * pair_coeff lines are placeholders the user must fill in — the cell
 * intentionally will NOT produce a physically meaningful run on first
 * click.
 */
export function buildLammpsExportCell(
  input: ExportTargetInput,
): ExportTemplate {
  const { slug, formula, parentStructureId } = input
  const code = [
    '# Export → LAMMPS native input (via ASE bridge).',
    `# Parent structure: ${slug} (${formula})`,
    '#',
    '# TODO before trusting any output:',
    '#   1. Set a real `pair_style` + `pair_coeff` for your system.',
    '#   2. Adjust `timestep`, `fix nvt/npt`, run length.',
    '#',
    '# The LAMMPS binary is `lmp` in the bundled conda environment.',
    '',
    'import subprocess',
    'from pathlib import Path',
    'from ase.io import write as ase_write',
    'from pymatgen.io.ase import AseAtomsAdaptor',
    '',
    `s = load_structure('${slug}')`,
    'atoms = AseAtomsAdaptor.get_atoms(s)',
    '',
    `DATA_PATH = Path('/tmp/data.${slug}')`,
    `IN_PATH = Path('/tmp/in.${slug}')`,
    '',
    '# Write the atoms + simulation box as a LAMMPS data file.',
    "ase_write(str(DATA_PATH), atoms, format='lammps-data')",
    '',
    '# Template input deck — edit before you care about results.',
    'in_text = f"""# Auto-generated by Lattice Export → LAMMPS.',
    'units         metal',
    'atom_style    atomic',
    'boundary      p p p',
    '',
    'read_data     {DATA_PATH}',
    '',
    '# TODO: replace with a real pair style for your system.',
    'pair_style    lj/cut 10.0',
    'pair_coeff    * * 1.0 1.0',
    '',
    'neighbor      2.0 bin',
    'neigh_modify  every 1 delay 0 check yes',
    '',
    'timestep      0.001',
    'thermo        50',
    'thermo_style  custom step temp pe ke etotal press',
    '',
    'fix           1 all nve',
    'run           200',
    '"""',
    'IN_PATH.write_text(in_text)',
    '',
    "print('data file:', DATA_PATH)",
    "print('input deck:', IN_PATH)",
    "print('--- running lmp ---')",
    "result = subprocess.run(",
    "    ['lmp', '-in', str(IN_PATH), '-log', 'none'],",
    '    capture_output=True, text=True, check=False,',
    ')',
    'print(result.stdout)',
    'if result.returncode != 0:',
    "    print('--- stderr ---')",
    '    print(result.stderr)',
    '',
  ].join('\n')
  return {
    cellKind: 'structure-code',
    title: `LAMMPS · ${formula}`,
    code,
    provenance: {
      ...(parentStructureId ? { parentStructureId } : {}),
      operation: 'export:lammps',
    },
  }
}

// ── CP2K (native cell) ─────────────────────────────────────────────

/**
 * Spawn a native `cp2k` cell whose body is a complete, self-contained
 * CP2K input deck. The lattice + atom coords from the ParsedCif are
 * inlined as &CELL and &COORD SCALED blocks; each unique element in
 * the structure gets its own &KIND block with a sensible default
 * basis set + pseudopotential. User can Run immediately; any errors
 * surface from cp2k.psmp itself.
 */
export function buildCp2kExportCell(
  input: ExportTargetInput,
): ExportTemplate {
  const { slug, formula, parentStructureId, parsedCif } = input
  const uniqueElements = Array.from(
    new Set(parsedCif.sites.map((s) => s.element)),
  ).sort()
  const unknown = uniqueElements.filter((e) => !(e in ELEMENT_DEFAULT_Q))

  const headerLines: string[] = []
  headerLines.push(`# Export → CP2K native input. Parent: ${slug} (${formula}).`)
  headerLines.push('# Run this cell and the container will pass it to cp2k.psmp.')
  if (unknown.length > 0) {
    headerLines.push(
      `# WARNING: unknown element(s) for default Q: ${unknown.join(', ')}.`,
    )
    headerLines.push(
      '# The &KIND block below falls back to POTENTIAL GTH-PBE (no -q suffix);',
      '# CP2K will reject this until you fill in the correct valence count.',
    )
  }

  const cp2k: string[] = []
  cp2k.push(...headerLines)
  cp2k.push('')
  cp2k.push('&GLOBAL')
  cp2k.push(`  PROJECT_NAME ${slug}`)
  cp2k.push('  RUN_TYPE ENERGY')
  cp2k.push('  PRINT_LEVEL LOW')
  cp2k.push('&END GLOBAL')
  cp2k.push('')
  cp2k.push('&FORCE_EVAL')
  cp2k.push('  METHOD QS')
  cp2k.push('  &DFT')
  cp2k.push('    BASIS_SET_FILE_NAME BASIS_MOLOPT')
  cp2k.push('    POTENTIAL_FILE_NAME GTH_POTENTIALS')
  cp2k.push('    &POISSON')
  cp2k.push('      PERIODIC XYZ')
  cp2k.push('    &END POISSON')
  cp2k.push('    &SCF')
  cp2k.push('      SCF_GUESS ATOMIC')
  cp2k.push('      MAX_SCF 50')
  cp2k.push('      EPS_SCF 1.0E-6')
  cp2k.push('    &END SCF')
  cp2k.push('    &XC')
  cp2k.push('      &XC_FUNCTIONAL PBE')
  cp2k.push('      &END XC_FUNCTIONAL')
  cp2k.push('    &END XC')
  cp2k.push('  &END DFT')
  cp2k.push('  &SUBSYS')
  cp2k.push('    &CELL')
  cp2k.push(`      A [angstrom] ${fmt(parsedCif.lattice.a)} 0.0 0.0`)
  cp2k.push(`      B [angstrom] 0.0 ${fmt(parsedCif.lattice.b)} 0.0`)
  cp2k.push(`      C [angstrom] 0.0 0.0 ${fmt(parsedCif.lattice.c)}`)
  // Note: only orthorhombic cells are correctly represented by this
  // simple A/B/C form. For triclinic cells (non-90° angles) the user
  // must edit the matrix — we emit a hint.
  const ortho = isOrthorhombic(parsedCif)
  if (!ortho) {
    cp2k.push(
      '      # TODO: lattice is not orthorhombic; replace the A / B / C vectors',
    )
    cp2k.push(
      '      #       above with the full Cartesian components for your cell.',
    )
  }
  cp2k.push('      PERIODIC XYZ')
  cp2k.push('    &END CELL')
  cp2k.push('    &COORD')
  cp2k.push('      SCALED')
  for (const site of parsedCif.sites) {
    cp2k.push(
      `      ${site.element} ${fmt(site.fx)} ${fmt(site.fy)} ${fmt(site.fz)}`,
    )
  }
  cp2k.push('    &END COORD')
  for (const el of uniqueElements) {
    const q = ELEMENT_DEFAULT_Q[el]
    const potential = q != null ? `GTH-PBE-q${q}` : 'GTH-PBE'
    cp2k.push(`    &KIND ${el}`)
    cp2k.push('      BASIS_SET DZVP-MOLOPT-SR-GTH')
    cp2k.push(`      POTENTIAL ${potential}`)
    cp2k.push('    &END KIND')
  }
  cp2k.push('  &END SUBSYS')
  cp2k.push('&END FORCE_EVAL')
  cp2k.push('')

  return {
    cellKind: 'cp2k',
    title: `CP2K · ${formula}`,
    code: cp2k.join('\n'),
    provenance: {
      ...(parentStructureId ? { parentStructureId } : {}),
      operation: 'export:cp2k',
    },
  }
}

// ── Internals ──────────────────────────────────────────────────────

function fmt(n: number, decimals = 6): string {
  return Number.isFinite(n) ? n.toFixed(decimals) : '0.000000'
}

function isOrthorhombic(parsed: ParsedCif): boolean {
  const { alpha, beta, gamma } = parsed.lattice
  return (
    Math.abs(alpha - 90) < 0.01 &&
    Math.abs(beta - 90) < 0.01 &&
    Math.abs(gamma - 90) < 0.01
  )
}

/**
 * Default valence-electron count matched to the `GTH-PBE-q<N>`
 * pseudopotential suffix. We bake in the ~20 most commonly-used
 * elements for inorganic materials work; anything outside this list
 * falls back to `GTH-PBE` (no suffix, which CP2K rejects — the error
 * is the right kind of loud for a user who doesn't know what q to
 * set).
 */
export const ELEMENT_DEFAULT_Q: Readonly<Record<string, number>> = {
  H: 1,
  Li: 3,
  Be: 4,
  B: 3,
  C: 4,
  N: 5,
  O: 6,
  F: 7,
  Na: 9,
  Mg: 10,
  Al: 3,
  Si: 4,
  P: 5,
  S: 6,
  Cl: 7,
  K: 9,
  Ca: 10,
  Ti: 12,
  V: 13,
  Cr: 14,
  Mn: 15,
  Fe: 16,
  Co: 17,
  Ni: 18,
  Cu: 11,
  Zn: 12,
  Ga: 13,
  Ge: 4,
  As: 5,
  Se: 6,
  Br: 7,
  Rb: 9,
  Sr: 10,
  Zr: 12,
  Nb: 13,
  Mo: 14,
  Ru: 16,
  Pd: 18,
  Ag: 11,
  Cd: 12,
  In: 13,
  Sn: 4,
  Sb: 5,
  Te: 6,
  I: 7,
  Cs: 9,
  Ba: 10,
  W: 14,
  Pt: 18,
  Au: 11,
  Pb: 4,
  Bi: 5,
}
