// Structure → Simulation Compute cell templates.
//
// Spawned from StructureArtifactCard's "Simulate ▾" menu. Every kind
// produces a `structure-code` Python cell (not native lammps / cp2k
// cells) because bridging CIF → LAMMPS or CIF → CP2K input is far
// cleaner via pymatgen inside one unified execution path than fighting
// each engine's native input syntax. User can always edit the spawned
// cell freely after the fact.

import type {
  ComputeCellKind,
  ComputeCellProvenance,
} from '../types/artifact'

export type SimulateKind = 'md-ase' | 'dft-cp2k' | 'py-play'

export interface SimulateTemplate {
  cellKind: ComputeCellKind
  title: string
  code: string
  provenance: ComputeCellProvenance
}

export interface SimulateTemplateInput {
  /** ACTIVE_CIFS slug — must match `slugForCifKey(artifact.title || formula || id)`. */
  slug: string
  /** Display label for the parent, e.g. "BaTiO3" — used in the title. */
  formula: string
  /** Source structure artifact id — wired into provenance so the cell
   *  header shows "← from structure <title>" and the StructureCard's
   *  "Used in" list can track this cell. */
  parentStructureId: string
}

export function buildSimulateTemplate(
  kind: SimulateKind,
  input: SimulateTemplateInput,
): SimulateTemplate {
  switch (kind) {
    case 'md-ase':
      return buildMdAseTemplate(input)
    case 'dft-cp2k':
      return buildDftCp2kTemplate(input)
    case 'py-play':
      return buildPyPlayTemplate(input)
  }
}

/**
 * Relax / MD via ASE's Langevin thermostat + a placeholder Lennard-Jones
 * calculator. We intentionally use LJ because it's parameter-free — the
 * user sees a runnable cell on click and then swaps in whatever
 * forcefield (EMT, effective-medium, MACE / M3GNet / pair_style through
 * ASE's LAMMPSlib) is appropriate. The goal is "one click → runnable
 * cell", not "one click → publication-grade MD".
 */
function buildMdAseTemplate(input: SimulateTemplateInput): SimulateTemplate {
  const { slug, formula, parentStructureId } = input
  const code = [
    '# Auto-generated by Simulate → Relax / MD (ASE + LJ).',
    `# Parent structure: ${slug} (${formula})`,
    '# TODO: replace LennardJones() with a real calculator for your system',
    '#   (EMT / ASE-LAMMPSlib / pymatgen-bridged M3GNet etc.) before',
    '#   reading anything into a paper.',
    '',
    'from ase.calculators.lj import LennardJones',
    'from ase.md.langevin import Langevin',
    'from ase import units',
    'from pymatgen.io.ase import AseAtomsAdaptor',
    '',
    `s = load_structure('${slug}')`,
    'atoms = AseAtomsAdaptor.get_atoms(s)',
    'atoms.calc = LennardJones()',
    '',
    'dyn = Langevin(',
    '    atoms,',
    '    timestep=1 * units.fs,',
    '    temperature_K=300,',
    '    friction=0.01,',
    ')',
    'dyn.run(200)',
    '',
    "print('final energy (eV):', atoms.get_potential_energy())",
    "print()",
    "print('--- relaxed CIF ---')",
    "print(AseAtomsAdaptor.get_structure(atoms).to(fmt='cif'))",
    '',
  ].join('\n')
  return {
    cellKind: 'structure-code',
    title: `MD · ${formula}`,
    code,
    provenance: {
      parentStructureId,
      operation: 'simulate:md-ase',
    },
  }
}

/**
 * DFT via pymatgen's CP2K IO. Writes a CP2K input file to /tmp and
 * invokes `cp2k` via subprocess — the container image ships both.
 * Kept as a **Python cell** rather than a raw CP2K cell because
 * pymatgen handles the cell + coord inlining robustly; users who
 * prefer hand-written CP2K input can convert after the fact.
 */
function buildDftCp2kTemplate(input: SimulateTemplateInput): SimulateTemplate {
  const { slug, formula, parentStructureId } = input
  const code = [
    '# Auto-generated by Simulate → DFT (CP2K via pymatgen).',
    `# Parent structure: ${slug} (${formula})`,
    '# TODO: review functional / cutoff / k-points before a production run —',
    '#   defaults here are deliberately small for a quick single-point.',
    '',
    'import subprocess, shlex, os',
    'from pymatgen.io.cp2k.inputs import Cp2kInput',
    'from pymatgen.io.cp2k.sets import StaticSet',
    '',
    `s = load_structure('${slug}')`,
    '',
    '# Fast-ish single-point — bump CUTOFF and tighten SCF for real runs.',
    'input_set = StaticSet(',
    '    structure=s,',
    '    project_name=f"{s.composition.reduced_formula}_scf",',
    '    cutoff=300,  # Ry',
    '    rel_cutoff=40,',
    ')',
    '',
    "INP = '/tmp/cp2k.inp'",
    "OUT = '/tmp/cp2k.out'",
    'input_set.write_input(output_dir=os.path.dirname(INP), make_dir_if_not_present=True)',
    '',
    "print('Wrote CP2K input to', INP)",
    "print('Running cp2k (single-point)…')",
    'proc = subprocess.run(',
    '    shlex.split(f"cp2k -i {INP} -o {OUT}"),',
    '    capture_output=True, text=True, timeout=300,',
    ')',
    "print('return code:', proc.returncode)",
    "print()",
    "print('--- tail of CP2K output ---')",
    "tail = open(OUT).read().splitlines()[-80:] if os.path.exists(OUT) else proc.stdout.splitlines()[-80:]",
    "print('\\n'.join(tail))",
    '',
  ].join('\n')
  return {
    cellKind: 'structure-code',
    title: `DFT · ${formula}`,
    code,
    provenance: {
      parentStructureId,
      operation: 'simulate:dft-cp2k',
    },
  }
}

/** Minimal pymatgen scratch pad seeded with `s = load_structure(...)`. */
function buildPyPlayTemplate(input: SimulateTemplateInput): SimulateTemplate {
  const { slug, formula, parentStructureId } = input
  const code = [
    `# Python playground for ${slug} (${formula}).`,
    '# `s` is a pymatgen Structure — add whatever analysis you like.',
    '',
    `s = load_structure('${slug}')`,
    'print(s.composition.reduced_formula, len(s), "sites")',
    'print("lattice:", s.lattice.abc, s.lattice.angles)',
    '',
    '# TODO: your code here',
    '',
  ].join('\n')
  return {
    cellKind: 'structure-code',
    title: `Playground · ${formula}`,
    code,
    provenance: {
      parentStructureId,
      operation: 'simulate:py-play',
    },
  }
}
