import type { CSSProperties } from 'react'
import { Cpu, Key } from 'lucide-react'

export const SECTION_ICONS = {
  resources: Cpu,
  env: Key,
}

export const S: Record<string, CSSProperties> = {
  wrap: {
    marginTop: 12,
    background: 'var(--color-bg-panel)',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  headerBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 14px',
    background: 'transparent',
    border: 'none',
    color: 'var(--color-text-secondary)',
    fontSize: 'var(--text-xs)',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'var(--font-sans)',
    textAlign: 'left' as const,
  },
  headerTitle: {
    flex: 1,
    fontSize: 'var(--text-xs)',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  body: {
    padding: '6px 14px 14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 16,
    borderTop: '1px solid var(--color-border)',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 'var(--text-xxs)',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    color: 'var(--color-text-muted)',
    marginTop: 4,
    marginBottom: 2,
    fontFamily: 'var(--font-sans)',
  },
  presets: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap' as const,
    marginBottom: 4,
  },
  sliderRow: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr 52px 28px',
    alignItems: 'center',
    gap: 10,
    fontSize: 'var(--text-xs)',
    fontFamily: 'var(--font-sans)',
  },
  slider: {
    width: '100%',
    accentColor: 'var(--color-accent)',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap' as const,
    fontSize: 'var(--text-xs)',
    padding: '2px 0',
    fontFamily: 'var(--font-sans)',
  },
  rowLabel: {
    flex: '0 0 100px',
    color: 'var(--color-text-secondary)',
  },
  radioLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    cursor: 'pointer',
  },
  toggleLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    cursor: 'pointer',
  },
  hint: {
    fontSize: 'var(--text-xxs)',
    color: 'var(--color-text-muted)',
  },
  hintInline: {
    fontSize: 'var(--text-xxs)',
    color: 'var(--color-text-muted)',
    textTransform: 'none' as const,
    letterSpacing: '0',
    fontWeight: 400,
  },
  numInput: {
    width: 72,
    background: 'var(--color-bg-input)',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    padding: '5px 8px',
    color: 'var(--color-text-primary)',
    fontSize: 'var(--text-xs)',
    outline: 'none',
    fontFamily: 'var(--font-mono)',
  },
  numInputInline: {
    width: 56,
    background: 'var(--color-bg-input)',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    padding: '5px 6px',
    color: 'var(--color-text-primary)',
    fontSize: 'var(--text-xs)',
    outline: 'none',
    fontFamily: 'var(--font-mono)',
    textAlign: 'right' as const,
  },
  unit: {
    fontSize: 'var(--text-xxs)',
    color: 'var(--color-text-muted)',
  },
  table: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  tableHead: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 55px 24px',
    gap: 8,
    fontSize: 'var(--text-xxs)',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    color: 'var(--color-text-muted)',
    padding: '0 2px',
    fontFamily: 'var(--font-sans)',
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 55px 24px',
    gap: 8,
    alignItems: 'center',
  },
  textInput: {
    background: 'var(--color-bg-input)',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    padding: '5px 8px',
    color: 'var(--color-text-primary)',
    fontSize: 'var(--text-xs)',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
    fontFamily: 'var(--font-sans)',
  },
  select: {
    background: 'var(--color-bg-input)',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    padding: '5px 8px',
    color: 'var(--color-text-primary)',
    fontSize: 'var(--text-xs)',
    outline: 'none',
    fontFamily: 'var(--font-sans)',
  },
  iconBtn: {
    background: 'transparent',
    border: '1px solid var(--color-border)',
    color: 'var(--color-text-muted)',
    borderRadius: 6,
    width: 24,
    height: 24,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    padding: '5px 12px',
    background: 'transparent',
    color: 'var(--color-text-secondary)',
    border: '1px dashed var(--color-border)',
    borderRadius: 6,
    fontSize: 'var(--text-xs)',
    cursor: 'pointer',
    fontFamily: 'var(--font-sans)',
    alignSelf: 'flex-start' as const,
    marginTop: 4,
  },
  emptyLine: {
    padding: '6px 2px',
    fontSize: 'var(--text-xxs)',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
    fontFamily: 'var(--font-sans)',
  },
}
