// Inline style dictionary for the Pro Workbench shell. Extracted from
// ProWorkbenchShell.tsx to keep the component file focused on layout
// and behaviour rather than token wiring.

import type { CSSProperties } from 'react'
import { PRO_TOOLBAR_HEIGHT } from '../tokens'
import { TYPO } from '../../../../../lib/typography-inline'

export const shellStyles: Record<string, CSSProperties> = {
  root: {
    flex: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: 'var(--color-bg-base)',
  },
  ribbon: {
    flexShrink: 0,
    height: PRO_TOOLBAR_HEIGHT,
    borderBottom: '1px solid var(--color-border)',
    background: 'var(--color-bg-sidebar)',
  },
  middle: {
    flex: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
  },
  railPlaceholder: {
    padding: '10px 6px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  railLabel: {
    writingMode: 'vertical-rl',
    transform: 'rotate(180deg)',
    fontSize: TYPO['2xs'],
    letterSpacing: '0.14em',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    textAlign: 'center',
  },
  railHint: {
    fontSize: TYPO.xxs,
    color: 'var(--color-text-muted)',
    padding: 6,
    lineHeight: 1.4,
  },
  mainColumn: {
    flex: 1,
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  mainViz: {
    flex: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    overflow: 'hidden',
  },
  hDivider: {
    flexShrink: 0,
    height: 4,
    cursor: 'row-resize',
    background: 'var(--color-border)',
  },
  vDivider: {
    flexShrink: 0,
    width: 4,
    cursor: 'col-resize',
    background: 'var(--color-border)',
  },
  inspectorScroll: {
    flex: 1,
    overflowY: 'auto',
    padding: '6px 0',
  },
  footer: {
    flexShrink: 0,
    borderTop: '1px solid var(--color-border)',
    background: 'var(--color-bg-sidebar)',
  },
  panelHeader: {
    flexShrink: 0,
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '2px 4px',
    borderBottom: '1px solid var(--color-border)',
    background: 'var(--color-bg-sidebar)',
  },
  panelBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  collapseBtn: {
    background: 'transparent',
    border: 'none',
    padding: '2px 4px',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    borderRadius: 3,
  },
  collapsedStripRight: {
    flexShrink: 0,
    width: 16,
    background: 'var(--color-bg-sidebar)',
    borderLeft: '1px solid var(--color-border)',
    cursor: 'pointer',
    color: 'var(--color-text-muted)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  collapsedStripBottom: {
    flexShrink: 0,
    height: 18,
    background: 'var(--color-bg-sidebar)',
    borderTop: '1px solid var(--color-border)',
    cursor: 'pointer',
    color: 'var(--color-text-muted)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    padding: 0,
    fontSize: TYPO.xxs,
    fontFamily: 'inherit',
    border: 'none',
    borderBottom: 'none',
  },
  collapsedStripLabel: {
    fontSize: TYPO.xxs,
    letterSpacing: '0.05em',
  },
}
